# -*- coding: utf-8 -*-
"""Delivery gate: burn the AIGC label, stamp the metadata, prove it read back.

GB 45438-2025 puts two independent obligations on generated video sold in China:
a visible label on the opening frames (5.4) and a machine-readable one in the
container (Annex E). A factory cannot ship without both, so this runs as a gate
rather than an option -- the metadata write refuses to return successfully if
the read-back does not show exactly one label.

Order matters and is not negotiable: burn first, stamp second. Re-encoding after
the metadata is written drops the metadata.

One rule added when the pipeline became portable: a cut assembled from
placeholder takes is refused here. A label that says "generated by AI" on
footage that is actually colour bars is a false declaration, and the whole point
of the null backend is that it can be run casually.
"""
from __future__ import annotations

import json
from pathlib import Path

from .aigc.label import (
    AigcMetadata, ExplicitLabelSpec, burn_explicit_label, resolve_cjk_font,
    write_aigc_metadata,
)
from .schema import Config
from .settings import Settings

LABEL_TEXT = "本视频由 AI 生成"
LABEL_SECONDS = 2.5


def deliver(st: Settings, cfg: Config, producer: str) -> dict:
    job = st.job(cfg.episode)
    src = job / "deliverables" / f"{cfg.episode}.mp4"
    if not src.is_file():
        raise SystemExit(f"nothing to deliver; run the edit stage first: {src}")

    edit_report = job / "edit-report.json"
    if edit_report.is_file():
        r = json.loads(edit_report.read_text(encoding="utf-8"))
        if r.get("placeholder_footage"):
            raise SystemExit(
                "refusing to deliver: this cut was assembled from null-backend "
                "placeholders. Configure a real render backend and re-run the "
                "render stage -- an AIGC label on colour bars is a false "
                "declaration, not a formality.")

    font = resolve_cjk_font(st.font_regular)
    burned = job / "deliverables" / f"{cfg.episode}.labelled.mp4"
    burn_explicit_label(
        src, burned,
        ExplicitLabelSpec(font_file=font, text=LABEL_TEXT,
                          position="top_left", duration_seconds=LABEL_SECONDS),
        ffmpeg=st.ffmpeg, ffprobe=st.ffprobe)

    final = job / "deliverables" / f"{cfg.episode}.delivery.mp4"
    verification = write_aigc_metadata(
        burned, final,
        AigcMetadata(label=1, content_producer=producer, produce_id=cfg.episode),
        ffmpeg=st.ffmpeg, ffprobe=st.ffprobe)

    report = {
        "delivery": str(final),
        "explicit_label": "burned, needs a human look (not machine verifiable)",
        "implicit_label_passed": verification.implicit_label_passed,
        "fields": list(verification.implicit_field_names or []),
        "failures": list(verification.failures or []),
    }
    (job / "deliver-report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=1), encoding="utf-8")
    if not verification.implicit_label_passed:
        raise SystemExit(json.dumps(report, ensure_ascii=False, indent=1))
    return report
